### ISSUE TITLE
ESP webserver-websocket wifi -serial bridge

### ISSUE THREAD

**Issue by mkeyno** [BerendWouters/WeatherStation#16]
sorry to open ticket for my question but honestly I couldn't figure out which part of your code would be help me out, actually I intend to use my special webserver-websocket program(Arduino IDE) in the ESP module to made Wifi -serial bridge with simple C# application , may I have your advice which part of source code would be helpful for me?
BR

**Comment by BerendWouters** [comment]
Well, in the https://github.com/BerendWouters/WeatherStation/tree/master/ESP8266Server folder you'll find the .ino-code to connect to a WiFi network (and much more).
The WebApp-code shows a typical MVC application in C#.

**Comment by mkeyno** [comment]
thanks for quick reply , actually I made my ESP  websocket-server side but I don't have enough skill in C# debugging , so I really appreciated if you direct me to handler function which is responsible to create  client websockt to ESP , simple thought would be like button on form which is pass IP&port data to that handler

**Comment by BerendWouters** [comment]
Well, the ESP doesn't directly connect to the webserver, but uses Azure's IoT hub for data processing. If you need to connect to a HTTP webserver, you might need a http client
